export type Genre = 'Fiction' | 'Non-Fiction' | 'Sci-Fi' | 'History' | 'Philosophy' | 'Business' | 'Psychology' | 'Biography'
export type Palette = 'ember' | 'twilight' | 'ocean' | 'gold' | 'forest' | 'dusk' | 'rose' | 'slate'

export interface Book {
  id: number
  title: string
  author: string
  genre: Genre
  description: string
  buyPrice: number
  rentPrice7: number
  rentPrice30: number
  rating: number
  pages: number
  year: number
  palette: Palette
  isbn: string
}

export function getCoverUrl(book: Book, size: 'S' | 'M' | 'L' = 'L'): string {
  return `https://covers.openlibrary.org/b/isbn/${book.isbn}-${size}.jpg`
}

export const books: Book[] = [
  { id: 1,  title: 'The Midnight Library',       author: 'Matt Haig',             genre: 'Fiction',     description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',                    buyPrice: 14.99, rentPrice7: 2.99, rentPrice30: 5.99, rating: 4.4, pages: 304, year: 2020, palette: 'twilight', isbn: '9780525559474'  },
  { id: 2,  title: 'Sapiens',                     author: 'Yuval Noah Harari',     genre: 'History',     description: 'A brief history of humankind, from the Stone Age to the present. How did our species come to dominate the planet and what does our future hold?',                                         buyPrice: 16.99, rentPrice7: 3.49, rentPrice30: 6.99, rating: 4.6, pages: 443, year: 2011, palette: 'gold',     isbn: '9780062316097'  },
  { id: 3,  title: 'Dune',                        author: 'Frank Herbert',          genre: 'Sci-Fi',      description: "Set in the distant future amid a feudal interstellar society, a noble family becomes embroiled in a war for the galaxy's most valuable resource.",                                        buyPrice: 12.99, rentPrice7: 2.49, rentPrice30: 4.99, rating: 4.8, pages: 896, year: 1965, palette: 'ember',    isbn: '9780441013593'  },
  { id: 4,  title: 'Atomic Habits',               author: 'James Clear',           genre: 'Non-Fiction', description: 'An easy and proven way to build good habits and break bad ones. Transform your life through tiny changes that deliver remarkable results.',                                               buyPrice: 15.99, rentPrice7: 3.29, rentPrice30: 6.49, rating: 4.7, pages: 320, year: 2018, palette: 'ocean',    isbn: '9780735211292'  },
  { id: 5,  title: 'The Republic',                author: 'Plato',                 genre: 'Philosophy',  description: 'The foundational text of Western philosophy. Socrates explores justice, beauty, equality, politics, and the ideal state through a series of dialogues.',                                  buyPrice: 9.99,  rentPrice7: 1.99, rentPrice30: 3.99, rating: 4.3, pages: 416, year: -380, palette: 'slate',    isbn: '9780140455113'  },
  { id: 6,  title: 'Thinking, Fast and Slow',     author: 'Daniel Kahneman',       genre: 'Psychology',  description: 'A landmark work in psychology about the two systems that drive the way we think — System 1, fast and intuitive, and System 2, slow and deliberate.',                                    buyPrice: 17.99, rentPrice7: 3.99, rentPrice30: 7.49, rating: 4.5, pages: 499, year: 2011, palette: 'forest',   isbn: '9780374533557'  },
  { id: 7,  title: 'Zero to One',                 author: 'Peter Thiel',           genre: 'Business',    description: 'Notes on startups, or how to build the future. The essential playbook for building a company that creates something truly new.',                                                         buyPrice: 13.99, rentPrice7: 2.79, rentPrice30: 5.49, rating: 4.3, pages: 224, year: 2014, palette: 'dusk',     isbn: '9780804139021'  },
  { id: 8,  title: 'The Name of the Wind',        author: 'Patrick Rothfuss',      genre: 'Fiction',     description: 'The riveting first-person narrative of Kvothe — magician, musician, and notorious figure. A tale of sorrow, love, and growing up extraordinary.',                                      buyPrice: 13.99, rentPrice7: 2.79, rentPrice30: 5.49, rating: 4.7, pages: 662, year: 2007, palette: 'rose',     isbn: '9780756404741'  },
  { id: 9,  title: 'Project Hail Mary',           author: 'Andy Weir',             genre: 'Sci-Fi',      description: 'A lone astronaut must save the earth from disaster. He remembers nothing of who he is or how he got here — and one discovery could mean the end for humanity.',                         buyPrice: 15.99, rentPrice7: 3.29, rentPrice30: 6.49, rating: 4.9, pages: 480, year: 2021, palette: 'ocean',    isbn: '9780593135204'  },
  { id: 10, title: 'Meditations',                 author: 'Marcus Aurelius',       genre: 'Philosophy',  description: 'Private notes of the Roman Emperor and Stoic philosopher — a series of spiritual exercises written as a source for his own guidance and self-improvement.',                              buyPrice: 8.99,  rentPrice7: 1.79, rentPrice30: 3.49, rating: 4.7, pages: 256, year: 170,  palette: 'slate',    isbn: '9780140449334'  },
  { id: 11, title: 'The Power of Now',            author: 'Eckhart Tolle',         genre: 'Non-Fiction', description: 'A guide to spiritual enlightenment through the practice of present-moment awareness. A transformative work that has helped millions find peace.',                                        buyPrice: 12.99, rentPrice7: 2.49, rentPrice30: 4.99, rating: 4.4, pages: 229, year: 1997, palette: 'gold',     isbn: '9781577314806'  },
  { id: 12, title: 'A Brief History of Time',     author: 'Stephen Hawking',       genre: 'Non-Fiction', description: 'From the Big Bang to black holes, Hawking explores the mysteries of the universe in clear, lucid prose accessible to anyone willing to grapple with the big questions.',              buyPrice: 11.99, rentPrice7: 2.29, rentPrice30: 4.49, rating: 4.5, pages: 212, year: 1988, palette: 'twilight', isbn: '9780553380163'  },
  { id: 13, title: 'Never Split the Difference',  author: 'Chris Voss',            genre: 'Business',    description: 'A former FBI hostage negotiator reveals the tactics and strategies that can change your life and your business — negotiating as if your life depended on it.',                          buyPrice: 14.99, rentPrice7: 2.99, rentPrice30: 5.99, rating: 4.6, pages: 288, year: 2016, palette: 'ember',    isbn: '9780062407801'  },
  { id: 14, title: "Man's Search for Meaning",    author: 'Viktor E. Frankl',      genre: 'Psychology',  description: 'A psychiatrist and Holocaust survivor describes his psychotherapeutic method of finding a reason to live, even in the most dire circumstances.',                                        buyPrice: 9.99,  rentPrice7: 1.99, rentPrice30: 3.99, rating: 4.8, pages: 165, year: 1946, palette: 'forest',   isbn: '9780807014295'  },
  { id: 15, title: 'The Innovators',              author: 'Walter Isaacson',       genre: 'Biography',   description: 'How a group of hackers, geniuses, and geeks created the digital revolution — the story of the people who created the computer and the internet.',                                      buyPrice: 18.99, rentPrice7: 3.99, rentPrice30: 7.99, rating: 4.5, pages: 560, year: 2014, palette: 'dusk',     isbn: '9781476708690'  },
  { id: 16, title: 'Crime and Punishment',        author: 'Fyodor Dostoevsky',     genre: 'Fiction',     description: 'An impoverished former student murders a pawnbroker for her money. But after the act, he must deal with his conscience, paranoia, and the detective investigating the crime.',         buyPrice: 10.99, rentPrice7: 2.19, rentPrice30: 4.29, rating: 4.6, pages: 671, year: 1866, palette: 'rose',     isbn: '9780140449136'  },
  { id: 17, title: 'The Lean Startup',            author: 'Eric Ries',             genre: 'Business',    description: "How today's entrepreneurs use continuous innovation to create radically successful businesses. A scientific approach to creating and managing successful startups.",                    buyPrice: 14.99, rentPrice7: 2.99, rentPrice30: 5.99, rating: 4.3, pages: 336, year: 2011, palette: 'ocean',    isbn: '9780307887894'  },
  { id: 18, title: 'Guns, Germs, and Steel',      author: 'Jared Diamond',         genre: 'History',     description: 'Why did history unfold differently on different continents? Diamond examines the factors that led to Eurasian civilizations dominating global history.',                                buyPrice: 16.99, rentPrice7: 3.49, rentPrice30: 6.99, rating: 4.4, pages: 480, year: 1997, palette: 'gold',     isbn: '9780393317558'  },
  { id: 19, title: 'The Pragmatic Programmer',    author: 'David Thomas',          genre: 'Non-Fiction', description: 'Your journey to mastery. A timeless classic for developers who want to write better code and build better software systems.',                                                           buyPrice: 19.99, rentPrice7: 4.49, rentPrice30: 8.99, rating: 4.7, pages: 352, year: 1999, palette: 'ember',    isbn: '9780135957059'  },
  { id: 20, title: 'Educated',                    author: 'Tara Westover',         genre: 'Biography',   description: "A memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",                                             buyPrice: 15.99, rentPrice7: 3.29, rentPrice30: 6.49, rating: 4.7, pages: 334, year: 2018, palette: 'forest',   isbn: '9780399590504'  },
  { id: 21, title: "Ender's Game",                author: 'Orson Scott Card',      genre: 'Sci-Fi',      description: 'The Earth is under attack from alien invaders. Ender Wiggin is trained at a battle school to be the ultimate military commander — not knowing the stakes.',                            buyPrice: 11.99, rentPrice7: 2.29, rentPrice30: 4.49, rating: 4.6, pages: 352, year: 1985, palette: 'twilight', isbn: '9780812550702'  },
  { id: 22, title: 'The Art of War',              author: 'Sun Tzu',               genre: 'Philosophy',  description: 'The ancient Chinese military treatise attributed to Sun Tzu. Its influence extends to business, management, and politics beyond military strategy.',                                   buyPrice: 7.99,  rentPrice7: 1.49, rentPrice30: 2.99, rating: 4.5, pages: 112, year: -500, palette: 'slate',    isbn: '9781590302255'  },
  { id: 23, title: 'The Psychology of Money',     author: 'Morgan Housel',         genre: 'Psychology',  description: 'Timeless lessons on wealth, greed, and happiness. How your relationship with money shapes your behavior — and what that means for investing and life.',                                buyPrice: 14.99, rentPrice7: 2.99, rentPrice30: 5.99, rating: 4.6, pages: 256, year: 2020, palette: 'dusk',     isbn: '9780857197689'  },
  { id: 24, title: 'Good to Great',               author: 'Jim Collins',           genre: 'Business',    description: "Why some companies make the leap to greatness and others don't. Based on a five-year research project comparing matched pairs of companies.",                                          buyPrice: 17.99, rentPrice7: 3.99, rentPrice30: 7.49, rating: 4.3, pages: 320, year: 2001, palette: 'rose',     isbn: '9780066620992'  },
  { id: 25, title: 'The Great Gatsby',            author: 'F. Scott Fitzgerald',   genre: 'Fiction',     description: 'A portrait of the Jazz Age in all of its decadence and excess. A critique of the American Dream set against the backdrop of the Roaring Twenties.',                                  buyPrice: 9.99,  rentPrice7: 1.99, rentPrice30: 3.99, rating: 4.1, pages: 180, year: 1925, palette: 'gold',     isbn: '9780743273565'  },
  { id: 26, title: 'Influence',                   author: 'Robert B. Cialdini',    genre: 'Psychology',  description: 'The psychology of persuasion. Six principles that govern how and why people say yes — weapons of influence that you can use ethically in your own life.',                             buyPrice: 14.99, rentPrice7: 2.99, rentPrice30: 5.99, rating: 4.5, pages: 336, year: 1984, palette: 'ember',    isbn: '9780061241895'  },
  { id: 27, title: '1984',                        author: 'George Orwell',         genre: 'Fiction',     description: 'A dystopian novel set in a totalitarian society ruled by Big Brother. A chilling prophetic vision of surveillance, thought control, and authoritarian rule.',                         buyPrice: 10.99, rentPrice7: 2.19, rentPrice30: 4.29, rating: 4.8, pages: 328, year: 1949, palette: 'twilight', isbn: '9780451524935'  },
  { id: 28, title: 'The Selfish Gene',            author: 'Richard Dawkins',       genre: 'Non-Fiction', description: 'A groundbreaking work in evolutionary biology that introduced the concept of the "selfish gene" and popularized gene-centered evolution.',                                           buyPrice: 13.99, rentPrice7: 2.79, rentPrice30: 5.49, rating: 4.4, pages: 360, year: 1976, palette: 'forest',   isbn: '9780192860927'  },
  { id: 29, title: 'Neuromancer',                 author: 'William Gibson',        genre: 'Sci-Fi',      description: 'The novel that defined cyberpunk. Henry Case is hired to pull off the ultimate hack — penetrating the Tessier-Ashpool ice that guards corporate data.',                              buyPrice: 12.99, rentPrice7: 2.49, rentPrice30: 4.99, rating: 4.3, pages: 271, year: 1984, palette: 'ocean',    isbn: '9780441569595'  },
  { id: 30, title: 'Leonardo da Vinci',           author: 'Walter Isaacson',       genre: 'Biography',   description: "A biography of the most creative genius in history, based on thousands of pages from Leonardo's astonishing notebooks.",                                                             buyPrice: 19.99, rentPrice7: 4.49, rentPrice30: 8.99, rating: 4.6, pages: 624, year: 2017, palette: 'dusk',     isbn: '9781501139154'  },
]

export function getBookById(id: number): Book | undefined {
  return books.find(b => b.id === id)
}

export function getBooksByGenre(genre: Genre): Book[] {
  return books.filter(b => b.genre === genre)
}

export const genres: Genre[] = ['Fiction', 'Non-Fiction', 'Sci-Fi', 'History', 'Philosophy', 'Business', 'Psychology', 'Biography']

export const featuredIds = [3, 9, 27, 2, 4, 6, 14, 23]
